# Generated by Django 4.2.2 on 2023-06-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(db_column='Cus_id', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Cus_name', max_length=30)),
            ],
        ),
    ]
