# Generated by Django 4.2.2 on 2023-06-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='CUS_NAME',
        ),
    ]
