# Generated by Django 4.2.2 on 2023-06-24 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0003_alter_goods_table'),
        ('customer', '0002_alter_customer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(db_column='Ord_date')),
                ('send_date', models.DateTimeField(db_column='Fin_date')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(db_column='COST_UNIT', decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(db_column='TOT_PRC', decimal_places=2, max_digits=10)),
                ('goods', models.ForeignKey(db_column='Goods_id', on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
            ],
            options={
                'db_table': 'D_ORDER',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('date', models.DateTimeField(auto_created=True, db_column='Order_Date')),
                ('id', models.CharField(db_column='Order_no', max_length=4, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(db_column='Cus_id', on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'H_ORDER',
            },
        ),
        migrations.CreateModel(
            name='Masterorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sys', models.DateTimeField(db_column='Sys_date')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(db_column='cost_tot', decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(db_column='Cus_id', on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.detail')),
                ('goods', models.ForeignKey(db_column='Goods_id', on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'M_ORDER',
            },
        ),
        migrations.AddField(
            model_name='detail',
            name='order',
            field=models.ForeignKey(db_column='Order_no', on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
