# Generated by Django 4.2.2 on 2023-06-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detail',
            table='D_ORDER',
        ),
        migrations.AlterModelTable(
            name='masterorder',
            table='M_ORDER',
        ),
        migrations.AlterModelTable(
            name='order',
            table='H_ORDER',
        ),
    ]
