# Generated by Django 4.2.2 on 2023-06-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.CharField(db_column='Goods_id', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Goods_name', max_length=30)),
                ('cost', models.DecimalField(db_column='cost_unit', decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
