# Generated by Django 4.2.2 on 2023-06-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name_plural': 'Goods'},
        ),
    ]
