# Generated by Django 4.2.2 on 2023-06-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goods_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='GOODS_NAME',
        ),
    ]
